CREATE TABLE `street_types` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`ID`)
);


CREATE TABLE `countries` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	`SHORT_NAME` VARCHAR(10) NOT NULL,
	`FLAG_IMAGE` BLOB,
	PRIMARY KEY (`ID`)
);


CREATE TABLE `cities` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	`AMOUNT_OF_PEOPLES` BIGINT(20),
	`COUNTRY_ID` BIGINT (20) NOT NULL,
	FOREIGN KEY (`COUNTRY_ID`) REFERENCES `countries`(`ID`),
	PRIMARY KEY (`ID`)
);


CREATE TABLE `streets` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	`STREET_TYPE_ID` BIGINT (20),
	`CITY_ID` BIGINT (20) NOT NULL,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`STREET_TYPE_ID`) REFERENCES `street_types`(`ID`),
	FOREIGN KEY (`CITY_ID`) REFERENCES `cities`(`ID`)
);


CREATE TABLE `houses` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	`STREET_ID` BIGINT (20),
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`STREET_ID`) REFERENCES `streets`(`ID`)
);
